# Generated by Django 3.2.6 on 2021-10-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_remove_event_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_event', models.CharField(max_length=200)),
                ('Booking_member', models.IntegerField(default=0)),
            ],
        ),
    ]
