# Generated by Django 3.2.6 on 2021-10-04 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_sponsor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ems.sponsor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ems.category'),
        ),
    ]
