# Generated by Django 3.2.6 on 2021-10-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_auto_20211004_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Booking_member',
        ),
        migrations.AlterField(
            model_name='booking',
            name='Booking_event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ems.event'),
        ),
    ]
