# Generated by Django 3.2.6 on 2021-10-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_auto_20211005_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Booking_username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='Date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='Your_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='Your_phone',
            field=models.IntegerField(default=0),
        ),
    ]
