# Generated by Django 3.2.6 on 2021-10-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_auto_20211005_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Booking_event',
            field=models.CharField(default='', max_length=100),
        ),
    ]
