# Generated by Django 3.2.6 on 2021-10-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0007_alter_booking_booking_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Register_fees',
            field=models.IntegerField(default=0),
        ),
    ]
