# Generated by Django 3.2.9 on 2010-01-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0008_booking_register_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='Your_Email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
