# Generated by Django 3.2.9 on 2010-01-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0009_auto_20100101_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1),
        ),
    ]
