# Generated by Django 3.2.9 on 2010-01-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0010_alter_booking_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Gender',
        ),
    ]
