# Generated by Django 3.2.9 on 2010-01-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0011_remove_booking_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_image',
            field=models.ImageField(default='', upload_to='static/media/event_img'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='Sponser_image',
            field=models.ImageField(default='', upload_to='static/media/sponser_img'),
        ),
    ]
